config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  get "search" => "searches#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
devise_for :users

  root to: "homes#top"
  get "home/about"=>"homes#about"


  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorite?(user)
   favorites.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_current_user, only: [:edit]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private


  def ensure_current_user
    @book = Book.find(params[:id])
    if current_user.id != @book.user.id
    flash[:notice]="権限がありません"
    redirect_to books_path
    end
  end



  def book_params
    params.require(:book).permit(:title, :image, :body)
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= image_tag book.user.get_profile_image(50,50) %>
          <% end %>
        </td>
        <td><%= link_to book.title,book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><% if book.favorite?(current_user) %>
            <%= link_to book_favorites_path(book.id), method: :delete do %>
              ♥<%= book.favorites.count %>
            <% end %>
            <% else %>
            <%= link_to book_favorites_path(book.id), method: :book do %>
              ♡<%= book.favorites.count %>
            <% end %>
            <% end %>
        </td>
        <td><%= "コメント数:#{book.book_comments.count} " %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のerrorが発生しました
      <ul>
    <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
      </ul>
  <% end %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
  <div class='col-md-8 offset-md-4'>
    <%= render 'searches/search' %>
  </div>
  </div>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のエラーが発生しました
      <ul>
    <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
      </ul>
  <% end %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to user_path(@user) do %>
            <%= image_tag @user.get_profile_image(100,100) %><br>
            <%= @user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title,book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td><% if @book.user == current_user %>
              <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %>
              <%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%>
              <% end %>
          </td>
            <td><% if @book.favorite?(current_user) %>
            <%= link_to book_favorites_path(@book.id), method: :delete do %>
              ♥<%= @book.favorites.count %> いいね
            <% end %>
            <% else %>
            <%= link_to book_favorites_path(@book.id), method: :book do %>
              ♡<%= @book.favorites.count %> いいね
            <% end %>
            <% end %>
            </td>
            </tr>
          </table>
            <div>
              <%= @book.book_comments.count %>
              <% @book.book_comments.each do |book_comment| %>
              <%= link_to user_path(book_comment.user) do %>
              <%= image_tag book_comment.user.get_profile_image(100,100) %>
                  <%= book_comment.user.name %>
                  <% end %>
              <%= book_comment.comment %>
              <% if book_comment.user == current_user %>
                <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
              <% end %>
              <% end %>
            </div>
          <div>
            <%= form_with model: [@book, @book_comment] do |f| %>
              <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに", class: "w-100" %>
              <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
            <% end %>
          </div>

    </div>
  </div>
</div>